# ArgoCD App: Deploy PrometheusRule cho SLO alerts
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/zacknguyn/cluster-security-gitops-demo.git
    path: app-alert
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
