apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password
  namespace: demo
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-password
  data:
  - secretKey: password
    remoteRef:
      key: w10/db-password
      property: password
